apiVersion: v1
kind: Secret
metadata:
  name: k8s-playground-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/steve-8000/k8s_playground
  password: ""
  username: ""
