apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 0gnft-db-pvc
  namespace: 0gnft
  labels:
    app: 0gnft-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-sc
