apiVersion: v1
kind: Service
metadata:
  name: zero-gnft-backend
  namespace: 0gnft
  labels:
    app: 0gnft-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: http
    protocol: TCP
  selector:
    app: 0gnft-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: zero-gnft-frontend
  namespace: 0gnft
  labels:
    app: 0gnft-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: 0gnft-frontend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: chainscan-proxy
  namespace: 0gnft
spec:
  type: ExternalName
  externalName: chainscan.0g.ai
  ports:
  - port: 443
    protocol: TCP
